"""update model changes

Revision ID: 0ef1fe97ea1c
Revises: 
Create Date: 2026-04-28 17:41:52.280744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0ef1fe97ea1c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctor_reviews', sa.Column('risk_override', sa.JSON(), nullable=False))
    op.drop_column('doctor_reviews', 'risk_overrides')
    # op.drop_index(op.f('ix_Reports_patient_id'), table_name='reports')
    op.create_index(op.f('ix_reports_patient_id'), 'reports', ['patient_id'], unique=False)
    op.drop_index(op.f('ix_Users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_Users_email'), 'users', ['email'], unique=True)
    op.drop_index(op.f('ix_reports_patient_id'), table_name='reports')
    op.create_index(op.f('ix_Reports_patient_id'), 'reports', ['patient_id'], unique=False)
    op.add_column('doctor_reviews', sa.Column('risk_overrides', mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'), nullable=False))
    op.drop_column('doctor_reviews', 'risk_override')
    # ### end Alembic commands ###
