"""test

Revision ID: 1af320843e19
Revises: 8dc8968c3288
Create Date: 2026-04-28 17:47:54.585244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1af320843e19'
down_revision: Union[str, Sequence[str], None] = '8dc8968c3288'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctor_reviews', sa.Column('risk_overrides', sa.JSON(), nullable=False))
    op.drop_column('doctor_reviews', 'risk_override')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctor_reviews', sa.Column('risk_override', mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'), nullable=False))
    op.drop_column('doctor_reviews', 'risk_overrides')
    # ### end Alembic commands ###
