"""new database

Revision ID: 39821447560b
Revises: 0ef1fe97ea1c
Create Date: 2026-04-28 17:45:37.083015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39821447560b'
down_revision: Union[str, Sequence[str], None] = '0ef1fe97ea1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('patient', 'doctor', name='user_role'), nullable=False),
    sa.Column('dob', sa.String(length=20), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('speciality', sa.String(length=255), nullable=True),
    sa.Column('license_number', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('reports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(length=1), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('height', sa.Float(), nullable=False),
    sa.Column('bmi', sa.Float(), nullable=False),
    sa.Column('glucose', sa.Float(), nullable=False),
    sa.Column('systolic_bp', sa.Float(), nullable=False),
    sa.Column('diastolic_bp', sa.Float(), nullable=False),
    sa.Column('cholesterol', sa.Float(), nullable=False),
    sa.Column('hemoglobin', sa.Float(), nullable=False),
    sa.Column('wbc_count', sa.Float(), nullable=False),
    sa.Column('creatinine', sa.Float(), nullable=False),
    sa.Column('platelet_count', sa.Float(), nullable=False),
    sa.Column('smoking_status', sa.String(length=20), nullable=False),
    sa.Column('alcohol_consumption', sa.String(length=20), nullable=False),
    sa.Column('physical_activity', sa.String(length=20), nullable=False),
    sa.Column('family_history', sa.String(length=20), nullable=False),
    sa.Column('symptoms', sa.String(length=255), nullable=False),
    sa.Column('predictions', sa.JSON(), nullable=False),
    sa.Column('shap_values', sa.JSON(), nullable=False),
    sa.Column('ensemble_confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'reviewed', 'follow-up', name='report_status'), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_patient_id'), 'reports', ['patient_id'], unique=False)
    op.create_table('doctor_reviews',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('report_id', sa.String(length=36), nullable=False),
    sa.Column('doctor_id', sa.String(length=36), nullable=False),
    sa.Column('diagnosis', sa.String(length=255), nullable=False),
    sa.Column('recommendations', sa.String(length=255), nullable=False),
    sa.Column('risk_override', sa.JSON(), nullable=False),
    sa.Column('follow_up_weeks', sa.Integer(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doctor_reviews_doctor_id'), 'doctor_reviews', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_doctor_reviews_report_id'), 'doctor_reviews', ['report_id'], unique=False)
    op.create_table('followups',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('report_id', sa.String(length=36), nullable=False),
    sa.Column('glucose', sa.Float(), nullable=True),
    sa.Column('systolic_bp', sa.Float(), nullable=True),
    sa.Column('diastolic_bp', sa.Float(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('feeling', sa.String(length=20), nullable=False),
    sa.Column('symptoms', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_followups_report_id'), 'followups', ['report_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.Enum('assessment', 'followup', name='notification_type'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.String(length=255), nullable=False),
    sa.Column('action_page', sa.String(length=255), nullable=True),
    sa.Column('report_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_followups_report_id'), table_name='followups')
    op.drop_table('followups')
    op.drop_index(op.f('ix_doctor_reviews_report_id'), table_name='doctor_reviews')
    op.drop_index(op.f('ix_doctor_reviews_doctor_id'), table_name='doctor_reviews')
    op.drop_table('doctor_reviews')
    op.drop_index(op.f('ix_reports_patient_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
