"""test

Revision ID: 6b2f9af500cf
Revises: 39821447560b
Create Date: 2026-04-28 17:46:19.431107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6b2f9af500cf'
down_revision: Union[str, Sequence[str], None] = '39821447560b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('statu', sa.Enum('pending', 'reviewed', 'follow-up', name='report_status'), nullable=True))
    op.drop_column('reports', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('status', mysql.ENUM('pending', 'reviewed', 'follow-up'), nullable=True))
    op.drop_column('reports', 'statu')
    # ### end Alembic commands ###
