"""added is_Active

Revision ID: 77887eca5b7c
Revises: 6c5ac8cdbbd2
Create Date: 2026-05-24 20:33:01.583403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '77887eca5b7c'
down_revision: Union[str, Sequence[str], None] = '6c5ac8cdbbd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False))
    op.alter_column('users', 'role',
               existing_type=mysql.ENUM('patient', 'doctor', 'admin'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=mysql.ENUM('patient', 'doctor', 'admin'),
               nullable=True)
    op.drop_column('users', 'is_active')
    # ### end Alembic commands ###
