"""changed schema for patient

Revision ID: 865fc1a9ee28
Revises: 3c60f82c86c6
Create Date: 2026-05-07 13:51:11.669181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '865fc1a9ee28'
down_revision: Union[str, Sequence[str], None] = '3c60f82c86c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('chest_pain_type', sa.String(length=20), nullable=False))
    op.add_column('reports', sa.Column('resting_ecg', sa.String(length=20), nullable=False))
    op.add_column('reports', sa.Column('resting_bp', sa.Float(), nullable=False))
    op.add_column('reports', sa.Column('st_slope', sa.String(length=20), nullable=False))
    op.add_column('reports', sa.Column('exercise_angina', sa.String(length=1), nullable=False))
    op.add_column('reports', sa.Column('fasting_bs', sa.Integer(), nullable=False))
    op.add_column('reports', sa.Column('max_hr', sa.Float(), nullable=False))
    op.add_column('reports', sa.Column('oldpeak', sa.Float(), nullable=False))
    op.drop_column('reports', 'diastolic_bp')
    op.drop_column('reports', 'systolic_bp')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('systolic_bp', mysql.FLOAT(), nullable=False))
    op.add_column('reports', sa.Column('diastolic_bp', mysql.FLOAT(), nullable=False))
    op.drop_column('reports', 'oldpeak')
    op.drop_column('reports', 'max_hr')
    op.drop_column('reports', 'fasting_bs')
    op.drop_column('reports', 'exercise_angina')
    op.drop_column('reports', 'st_slope')
    op.drop_column('reports', 'resting_bp')
    op.drop_column('reports', 'resting_ecg')
    op.drop_column('reports', 'chest_pain_type')
    # ### end Alembic commands ###
