"""test

Revision ID: 8dc8968c3288
Revises: 6b2f9af500cf
Create Date: 2026-04-28 17:47:14.327737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8dc8968c3288'
down_revision: Union[str, Sequence[str], None] = '6b2f9af500cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('status', sa.Enum('pending', 'reviewed', 'follow-up', name='report_status'), nullable=True))
    op.drop_column('reports', 'statu')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('statu', mysql.ENUM('pending', 'reviewed', 'follow-up'), nullable=True))
    op.drop_column('reports', 'status')
    # ### end Alembic commands ###
