"""added risk_level

Revision ID: c61be402812f
Revises: ea53de4aaf0d
Create Date: 2026-05-01 23:42:26.731568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c61be402812f'
down_revision: Union[str, Sequence[str], None] = 'ea53de4aaf0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('risk_level', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'risk_level')
    # ### end Alembic commands ###
