"""test

Revision ID: ea53de4aaf0d
Revises: 1af320843e19
Create Date: 2026-04-28 17:48:51.187720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ea53de4aaf0d'
down_revision: Union[str, Sequence[str], None] = '1af320843e19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctor_reviews', sa.Column('risk_override', sa.JSON(), nullable=False))
    op.drop_column('doctor_reviews', 'risk_overrides')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctor_reviews', sa.Column('risk_overrides', mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'), nullable=False))
    op.drop_column('doctor_reviews', 'risk_override')
    # ### end Alembic commands ###
