"""changed reports model

Revision ID: eec0a56d9198
Revises: 865fc1a9ee28
Create Date: 2026-05-07 18:11:41.145962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eec0a56d9198'
down_revision: Union[str, Sequence[str], None] = '865fc1a9ee28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('recommendations', sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'recommendations')
    # ### end Alembic commands ###
